export const SEND_EMAIL_REQUEST = "SEND_EMAIL_REQUEST"; 
export const SEND_EMAIL_SUCCESS = "SEND_EMAIL_SUCCESS"; 
export const SEND_EMAIL_ERROR = "SEND_EMAIL_ERROR"; 

export const GET_EMAIL_REQUEST = "GET_EMAIL_REQUEST" ; 
export const GET_EMAIL_SUCCESS = "GET_EMAIL_SUCCESS" ; 
export const GET_EMAIL_ERROR = "GET_EMAIL_ERROR"  ;    

export const GET_STATISTICS_REQUEST = "GET_STATISTICS_REQUEST" ; 
export const GET_STATISTICS_SUCCESS = "GET_STATISTICS_SUCCESS" ; 
export const GET_STATISTICS_ERROR = "GET_STATISTICS_ERROR"  ;  

